### PR TITLE
dylan: rework bluetooth systemd support

### PR DESCRIPTION
**Pull request by pabigot**
I've been refamiliarizing myself with gumstix and notice that some recent commits are related to a bluetooth UART feature I did in January for a potential client but never released.  I've updated that feature in the commit in this pull request.

The primary value I see in this version is it introduces the necessary systemd dependencies to make sure bluetooth is enabled along with bluetooth-hciattach.  Without that dependency---or subsequent patches that are reverted in this pull---the device isn't really created and usable (at least not as far as I can tell; hcitool dev won't show it).  I've also provided a way to customize the the UART features, and a sample service that provides a login prompt over the bluetooth link.

This sequence also reverts the recent changes 9e5dd9bacc and cacc4598 to enable bluetooth services by default.  The reason they got complicated is because systemd support for bluetooth is not in the bluez recipe, it's in a bbappend added by the OE Core layer.  In that layer SYSTEMD_AUTO_ENABLE's default is overridden to be "disabled".  Analogously, the original version of the secondary bbappend in meta-gumstix simply overrode, rather than extended, the original bbappend's SYSTEMD_SERVICE variable.

The systemd dependencies in this version should make much of that unnecessary: specifically, if you enable ttyO1 you get the stuff required to make it work.  I haven't incorporated support for the final change to to enable all bluetooth services by default, because (a) I finished this before noticing that commit, (b) I'm unclear what good enabling bluetooth-ttyO1 does without something that uses it; and (c) I don't think the new bluetooth-sp should be enabled by default because it does cause kernel panics under Linux 3.5 when the rfcomm0 tty disappears.  (It works fine under my 3.8 linux-yocto--based kernel.)

Note that "systemctl enable bluetooth-ttyO1.service" does not enable bluetooth.service; but subsequently starting bluetooth-ttyO1.service will cause bluetooth.service to be started even though it isn't enabled in its own right.

So consider this an opportunity for discussion, or if you like use it as a reference to apply any subset of the features that you think are valuable.

### CODE REVIEW

**Comment by ashcharles** [comment]
Thanks for the pull request.  This looks good to me but I'm away from my desk until Monday and I'd like to give it a quick whirl first.

**Comment by pabigot** [comment]
On further reflection and after playing with some PAN stuff, I think this sort of thing really belongs in a separate recipe rather than appended to the standard one.

**Comment by ashcharles** [comment]
The reverts seem reasonable to me.  The original appends should have been
more carefully constructed.
The third commit can be broken down into some chunks:
1. Correcting the mistakes that required reverts.  This is good.
2. Sets a dependency for our bluetooth service on the existence of ttyO1.
3. Adds a serial port service via Bluetooth.  This is an extra and should
be broken out separately.
4. Allows for a configuration file with some default values.  Reasonable
for SDP but the communication parameters for ttyO1 are fixed on Overo.

Suggestions on how best to treat this pull request for 1.4?  I'm tempted to
accept the reverts and chunks #1 and #2 but leave out the SDP additions.

--Ash

**Comment by pabigot** [comment]
I think the right answer is take the reverts, and add a new gumstix-bluetooth recipe to support the HCI stuff.  The latter can just re-use the service units (at least bluetooth-ttyO1.service).  These gumstix-specific services do not belong in the generic bluez4 package.

**Comment by pabigot** [comment]
On third thought, if bluetooth is absolutely unusable without the hciattach (for which there is some evidence), then it does make sense to put it int the bluez package.  In fact, the changes arguably belong in the BSP layer in that case.

I'm going to be playing with connman today to see if the dylan version can handle bluetooth networking and may be able to provide an alternative solution soon if you don't already have this in work.

**Comment by pabigot** [comment]
I've updated this to remove all the bluetooth mods from meta-gumstix-extras.  A new solution that does this very nicely is going to be submitted for meta-gumstix.

I'll hold off on adding the SP service (via a new recipe in extras) until gumstix has a kernel that doesn't panic when it's used.

**Comment by ashcharles** [comment]
Thanks Peter.
meta-gumstix is definitely the right target.
--Ash

**Comment by ashcharles** [comment]
Closing as this is was fixed in meta-gumstix.

**Comment by pabigot** [comment]
Have you pulled the reverts but not yet pushed them to github?  meta-gumstix-extras has higher priority than meta-gumstix so unless the bluez mods in this repository were removed first the service file in the final package will be the wrong version.

**Comment by ashcharles** [comment]
Just pushed reverts on
1ae1c55783128c00bafc7ea948e6c37c5075dc15
9e5dd9bacc989784aadf0c1c5419515a10883869
cacc4598b080f6c119b0dc0e77439013baa89536

**Pull request closed without merging**
